version: "3.3"

volumes:
  mysql-volume:

networks:
  database:
    driver: bridge

services:
  mysql:
    image: "bitnami/mysql:8.0.32"
    restart: always
    networks:
      - database
    environment:
      MYSQL_ROOT_USER: my_root_user
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: &db_name snippetbox
      MYSQL_USER: &db_user my_user
      MYSQL_PASSWORD: &db_pwd my_password
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - mysql-volume:/bitnami/mysql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5

  snippetbox:
    build:
      context: ./
    restart: on-failure
    networks:
      - database
    depends_on:
      - mysql
    environment:
      DB_USER: *db_user
      DB_PWD: *db_pwd
      DB_ADDR: mysql:3306
      DB_NAME: *db_name
    ports:
      - "8080:8080"
